name: Deployment - Reusable

on:
  workflow_call:
    inputs:
      mongodb-uri:
        required: true
        type: string
      kubectl-version:
        description: Provide the required Kubectl version
        default: v1.26.0
        required: false
        type: string
      k8s-manifest-dir:
        description: Directory containing K8s manifests files
        default: kubernetes/
        required: true
        type: string
      environment:
        description: Provide the deployment environment
        default: dev
        required: true
        type: string

    outputs:
      application-url:
        value: ${{ jobs.reuse-deploy.outputs.APP_INGRESS_URL }}
    
    secrets:
      k8s-kubeconfig:
        required: true
      mongodb-password:
        required: true
        
jobs:
  reuse-deploy:
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}

    outputs:
      APP_INGRESS_URL: https://${{ steps.set-ingress-host-address.outputs.APP_INGRESS_HOST }}
    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Kubectl CLI
        uses: azure/setup-kubectl@v3
        with:
          version: '${{ inputs.kubectl-version }}'

      - name: Set Kubeconfig file
        uses: azure/k8s-set-context@v3

## ....
    #   - name:

